# Generated by Django 2.0.1 on 2018-02-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barreslabrnaseqrawdatamodules',
            options={'managed': False},
        ),
    ]
