# Generated by Django 2.0.1 on 2018-02-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_auto_20180223_2340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barreslabrnaseqrawdatamodules',
            table='barreslab_rnaseq_raw_data_modules',
        ),
    ]
