# Generated by Django 2.0.1 on 2018-03-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_auto_20180223_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barreslabrnaseqrawdata',
            options={'managed': False},
        ),
    ]
