# Generated by Django 2.0.1 on 2018-03-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0004_auto_20180228_1920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barreslabrnaseqrawdata',
            table='barreslab_rnaseq_raw_data',
        ),
    ]
